apiVersion: v1
kind: Service
metadata:
  name: logstash-headless
  namespace: default
  labels: 
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  - name: http
    port: 5044
    targetPort: http
    protocol: TCP
  selector: 
    app: logstash
