apiVersion: v1
kind: Service
metadata:
  name: logstash
  namespace: default
  labels: 
    app: logstash
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 5044
    targetPort: http
    protocol: TCP
  selector: 
    app: logstash
